Add robust focused tests rule
wix/tslint-config-wix pull request #7
Opened 2018-01-01 18:46 UTC by felixmosh

2018-01-01 22:25 UTC, roymiloh approved these changes

2018-01-02 09:36 UTC, ranyitz requested changes
Thanks for the contribution!
That looks great,
I would just add messages to the ban rule, maybe something like this.

```json
"ban": [
      true,
      {"name": "fdescribe", "message": "no-focused-test"},
      {"name": "fit", "message": "no-focused-test"},
      {"name": ["it", "only"], "message": "no-focused-test"},
      {"name": ["describe", "only"], "message": "no-focused-test"}
    ]
```

2018-01-02 09:36 UTC, ranyitz commented on test/scripts/no-jasmine-focus/invalid.describe.only.ts
> +describe.only('test me', () => {
I would change the directory name to `no-focus-test` instead of `no-jasmine-focus`

2018-01-02 09:36 UTC, ranyitz commented on tslint.json
> +      "fdescribe",
please add message

2018-01-02 09:58 UTC, felixmosh commented
Done, thanx

2018-01-02 10:07 UTC, ranyitz approved these changes
Awesome, Thanks.

2018-01-09 18:51 UTC, shahata commented
@ranyitz why isn't it merged?

2018-01-09 21:56 UTC, merged